# Crash Course for Python 3

In [1]:
import numpy as np

### Arrays (import numpy)

In [2]:
array1 = np.array([1,4,9])
array2 = np.array([1,"s",23])
array3 = np.array([[1,2,3],[4,5,6]])

In [3]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

Select elements

In [4]:
print(array1[1])
print(array2[0:2])
print(array3[1,2])

4
['1' 's']
6


Manipulate

In [5]:
array1 = np.append(array1, 7)
print(array1)

[1 4 9 7]


In [6]:
array1 = np.append(array1, np.array([76, 41]))
print(array1)


[ 1  4  9  7 76 41]


Manipulate multi-dimensional arrays

In [7]:
array3 = np.append(array3, np.array([[9,9,9]]), axis=0)
print(array3)

[[1 2 3]
 [4 5 6]
 [9 9 9]]


In [8]:
array3 = np.append(array3, np.array([[0,8],[0,8],[0,8]]), axis=1)
print(array3)

[[1 2 3 0 8]
 [4 5 6 0 8]
 [9 9 9 0 8]]


Maths

In [9]:
array1 = array1*2

In [10]:
array1 = array1+2
print(array1)

[  4  10  20  16 154  84]


### Vectors and Matrices

### Vectors

In [16]:
vec1 = np.array([1,1,1])
vec2 = np.array([2,3,4])

Dot and cross product

In [17]:
np.dot(vec1,vec2)

9

In [19]:
print(np.cross(vec1,vec2))
print(np.cross(vec2,vec1))

[ 1 -2  1]
[-1  2 -1]


Norm

In [24]:
np.linalg.norm(vec1)

1.7320508075688772

In [26]:
norm = np.sqrt(vec1[0]**2+vec1[1]**2+vec1[2]**2)
print(norm)

1.7320508075688772


### Matrices

Multiplication

Determinant and inverse

### Dictionaries

Select entries

Manipulate entries

## Loops & If statements

### While loop

### While loop with if statement

### For loop

## Work with files

### Save

Save the whole list at once

Save each line one after another

### Load

## Functions

def _name_(_arguments_):

    commands

First function without arguments

Create your own dot product function

Use argument keywords

## Plots (import matplotlib)

In [149]:
import matplotlib.pyplot as plt

### Scatter

### Plot

### Density plot

### 3d plots

### 3d plots - lines & scatter plot